name: cloud_firestore_server
description: Server-side Firestore for your backend in Dart.
# version: 1.0.0
homepage: https://www.sharezone.net
environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety
  googleapis: ^0.56.1
  googleapis_auth: ^0.2.12
  http: ^0.12.2
  meta: ^1.3.0-nullsafety
  quiver: ^3.0.0-nullsafety
  
dev_dependencies: 
  lint: ^1.3.0
  test: ^1.16.0-nullsafety
